#!/bin/sh

# This file installs the modified why3 and statwhy.

# Usage: ./statwhy-install.sh INSTALL_DIRECTORY OPAM_SWITCH
# The current directory must be the modified why3 source directory
#
# This installation modifies following files/directories:
#
# - INSTALL_DIRECTORY
# - $HOME/.opam/OPAM_SWITCH
# - $HOME/.profile                      # add opam configuration
# - $HOME/.why3.conf                    # why3 configuration
# - $HOME/.statwhy.conf                 # statwhy configuration
#
# Example:
#   This uses $HOME/statwhy and $HOME/.opam/statwhy.
#   env-why3 sets several environment variables.
#
#   % git clone --depth 1 --branch python-real http://host/path/why3-py.git
#   % cd why3-py
#   % ./statwhy-install.sh $HOME/statwhy statwhy
#   % eval $(opam env)
#   % PATH=$HOME/statwhy/bin:$PATH
#   % ./env-why3 python examples/statwhy-python/executable_examples/ex_chi2_contingency.py
#   0.03749647249996269
#   % ./env-why3 why3 ide --debug=python --debug=ide_info --debug=scheduler examples/statwhy-python/executable_examples/ex_chi2_contingency.py --extra-config $HOME/.statwhy.conf

if [ $# -eq 0 ]; then
  echo "Usage: ./statwhy-install.sh INSTALL_DIRECTORY OPAM_SWITCH" >&2
  exit 1
fi

D="${1:?INSTALL_DIRECTORY not specified.  Specify it as the first argument}"
opam_switch="${2:?OPAM_SWITCH not specified.  Specify it as the second argument}"

STATWHY_WHY3_SRC_DIR="$(cd "$(dirname "$0")" && pwd)"
STATWHY_TARGET_DIR="$D"
STATWHY_OPAM_SWITCH="$opam_switch"

(
  echo "# this file is generated by statwhy-install.sh"
  echo "STATWHY_WHY3_SRC_DIR='$STATWHY_WHY3_SRC_DIR'"
  echo "STATWHY_TARGET_DIR='$STATWHY_TARGET_DIR'"
  echo "STATWHY_OPAM_SWITCH='$STATWHY_OPAM_SWITCH'"
) > "$STATWHY_WHY3_SRC_DIR/.statwhy-install.config"

case "$D" in
/*) ;;
*) echo "install-directory must start with /" >&2
  exit 1
   ;;
esac

# required debian packages
#
# opam
# git
# wget
# ca-certificates               # https access (opam, pip)
# build-essential               # python
# libsqlite3-dev                # python (sqlite module)
# libssl-dev                    # python (ssl module)
# ca-certificates               # opam
# rsync                         # opam
# pkgconf                       # why3
# autoconf                      # why3
# cvc5                          # why3
# libgmp-dev                    # why3
# libcairo2-dev                 # why3-ide
# libgtk-3-dev                  # why3-ide
# libgtksourceview-3.0-dev      # why3-ide

if [ -e "$D" ]; then
  echo "[skip] statwhy install directory already exists \"$D\"."
else
  echo "[do] mkdir $D"
  mkdir "$D" || exit 1
fi

if [ -e "$HOME/.opam" ]; then
  echo "[skip] opam already initialized."
else
  echo "[do] opam init"
  # modify ~/.profile.
  opam init --shell-setup || exit 1
fi

if [ -e "$HOME/.opam/$opam_switch" ]; then
  echo "[skip] opam switch already exists \"$HOME/.opam/$opam_switch\"."
else
  echo "[do] create opam switch"
  opam switch create "$opam_switch" --packages=ocaml-option-flambda.1,ocaml-variants.5.0.0+options || exit 1
fi

eval $(opam env --switch="$opam_switch")

if [ -e "$D/bin/python3.14" ]; then
  echo "[skip] python3.14 already installed."
else
  echo "[do] install python3.14"
  (
    cd "$D/$dir" &&
    (test -f Python-3.14.4.tar.xz ||
     wget https://www.python.org/ftp/python/3.14.4/Python-3.14.4.tar.xz) &&
    tar xf Python-3.14.4.tar.xz &&
    cd Python-3.14.4 &&
    ./configure --prefix="$D" &&
    make &&
    make install
  ) || exit 1
fi

install_python_package() {
  pkg="$1"

  if "$D/bin/pip3" list | grep -q "^${pkg} "; then
    echo "[skip] ${pkg} already installed."
  else
    echo "[do] install ${pkg}."
    "$D/bin/pip3" install "${pkg}" || exit 1
  fi
}

install_python_package scipy
install_python_package scipy-stubs
install_python_package scikit-posthocs
install_python_package no-manylinux     # disable binary package (disable Cython) for mypy
install_python_package mypy

install_opam_package() {
  pkg="$1"
  version="$2"

  if opam list --short | grep -q "^$pkg\$"; then
    echo "[skip] $pkg already installed."
  else
    echo "[do] install $pkg."
    opam install -y $pkg.$version || exit 1
  fi
}

# The version constraint of these packages are different for why3 and cameleer.
# So, installing them with right versions at beginning avoids recompiling why3 when installing cameleer.

install_opam_package sexplib0 v0.16.0
install_opam_package sexplib v0.16.0
install_opam_package ppx_sexp_conv v0.16.0
install_opam_package ppx_deriving 6.0.3

if opam list --short | grep -q '^why3$'; then
  echo "[skip] why3 already installed."
else
  echo "[do] install modified why3."
  opam pin add -y --working-dir --with-version=1.8.0 why3 . || exit 1
  opam pin add -y --working-dir --with-version=1.8.0 why3-ide . || exit 1
fi

git_clone_or_pull() {
  dir="$1"
  repo="$2"

  if [ -d "$D/$dir" ]; then
    echo "[pull] pull latest $dir."
    (cd "$D/$dir" && git pull)
  else
    echo "[do] clone $dir."
    git clone --depth 1 "$repo" "$D/$dir" || exit 1
  fi
}

git_clone_or_pull statwhy https://github.com/fm4stats/statwhy.git

if opam list --short | grep -q '^cameleer$'; then
  echo "[skip] cameleer(statwhy) already installed."
else
  echo "[do] install statwhy(cameleer)."
  (cd "$D/statwhy/cameleer" && opam pin add . -y --working-dir --with-version=0.1) || exit 1
fi

export PATH="$D/bin:$PATH"

why3 config detect || exit 1    # creates ~/.why3.conf

statwhy --genconf || exit 1     # creates ~/.statwhy.conf


# uninstall:
# opam switch remove OPAM_SWITCH
# rm -rf INSTALL_DIRECTORY
